
	######################################
	#START CONFIGURATION (Re:Markers)
	######################################

	#Install neccessary packages if not installed already. Remove hashtag from relevant lines below
	#install.packages("readxl") #read excel files
	#install.packages("ggplot2") #graphing

	#Working Directory (effective)
	setwd("C:/Users/Local Admin/Documents/RStudio Projects/")
	
	#Clear Environment
	rm(list=ls())


	######################################
	#END CONFIGURATION
	######################################

	#Define any external libraries that we will be using in our code

	library("readxl") #read excel files
	library("ggplot2") #Graphing
	#Affects all graphs generated by this file
	theme_set(theme_gray(base_size = 18))
	legend_table <- cbind(c(#Generic Abbreviations
							'Code','Label','Year',
							#First Excel Sheet Abbreviatoins
							'ERP_P_P_1','ERP_P_P_2','ERP_P_P_3','ERP_P_P_4','ERP_P_P_5','ERP_P_P_6','ERP_P_P_7','ERP_P_P_8','ERP_P_P_9',
							'ERP_M_1','ERP_M_2','ERP_M_3','ERP_M_4','ERP_M_5','ERP_M_6','ERP_M_7','ERP_M_8','ERP_M_9','ERP_M_10','ERP_M_11','ERP_M_12','ERP_M_13',
							'ERP_M_14','ERP_M_15','ERP_M_16','ERP_M_17','ERP_M_18','ERP_M_19','ERP_F_1','ERP_F_2','ERP_F_3','ERP_F_4','ERP_F_5','ERP_F_6',
							'ERP_F_7','ERP_F_8','ERP_F_9','ERP_F_10','ERP_F_11','ERP_F_12','ERP_F_13','ERP_F_14','ERP_F_15','ERP_F_16','ERP_F_17','ERP_F_18',
							'ERP_F_19','ERP_P_N_1','ERP_P_N_2','ERP_P_N_3','ERP_P_N_4','ERP_P_N_5','ERP_P_N_6','ERP_P_N_7','ERP_P_N_8','ERP_P_N_9','ERP_P_N_10',
							'ERP_P_N_11','ERP_P_N_12','ERP_P_N_13','ERP_P_N_14','ERP_P_N_15','ERP_P_N_16','ERP_P_N_17','ERP_P_N_18','ERP_P_N_19', 'ERP_WAP','ERP_MA_1',
							'ERP_MA_2','ERP_MA_3','BaD_1','BaD_2','BaD_3','BaD_4','PopDense','Abo_TorIsl','OBP_1','OBP_2','OBP_3','OBP_4','OBP_5','OBP_6','OBP_7',
							'OBP_8','OBP_9','OBP_10','RIME_1','RIME_2','RIME_3',
							#Second Excel Sheet Abbreviations
							'NoB_1','NoB_2','NoB_3','NoB_4','NoB_5','BEntry_1','BEntry_2','BEntry_3','BEntry_4','BEntry_5',
							'BExit_1','BExit_2','BExit_3','BExit_4','BExit_5','NoBbI_1','NoBbI_2','NoBbI_3','NoBbI_4','NoBbI_5','NoBbI_6','NoBbI_7',
							'NoBbI_8','NoBbI_9','NoBbI_10','NoBbI_11','NoBbI_12','NoBbI_13','NoBbI_14','NoBbI_15','NoBbI_16','NoBbI_17','NoBbI_18','NoBbI_19',
							'NoBbI_20','NoBbI_21','BA_1','BA_2','BA_3','BA_4','BA_5','BA_6','BA_7','BA_8','BA_9','BA_10','RPP_1','RPP_2','RPP_3','RPP_4',
							'BankR_1','BankR_2','BankR_3','EbI_1','EbI_2','EbI_3','EbI_4','EbI_5','EbI_6','EbI_7','EbI_8','EbI_9','EbI_10','EbI_11','EbI_12',
							'EbI_13','EbI_14','EbI_15','EbI_16','EbI_17','EbI_18','EbI_19','EbI_20','RMV_V_1','RMV_V_2','RMV_V_3','RMV_V_4','RMV_V_5','RMV_V_6',
							'RMV_V_7','RMV_V_8','RMV_V_9','RMV_V_10','RMV_F_1','RMV_F_2','RMV_F_3','RMV_F_4','RMV_M_1','RMV_M_2','RMV_M_3',
							#Third Excel Sheet Abbreviations
							'EoPI_1','EoPI_2','EoPI_3','EoPI_4','EoPI_5','EoPI_6','EoPI_7','EoPI_8','EoPI_9','EoPI_10','EoPI_11','EoPI_12','EoPI_13','EoPI_14',
							'EoPI_15','EoPI_16','EoPI_17','EoPI_18','SGPaA_1','SGPaA_2','SGPaA_3','SGPaA_4','SGPaA_5','SGPaA_6','SGPaA_7','SGPaA_8','SGPaA_9',
							'SGPaA_10','SGPaA_11','SGPaA_12','SGPaA_13','SGPaA_14','PwPSQ_1','PwPSQ_2','PwPSQ_3','PwPSQ_4','PwPSQ_5','PwPSQ_6','PwPSQ_7','OoEP_1',
							'OoEP_2','OoEP_3','OoEP_4','OoEP_5','OoEP_6','OoEP_7','OoEP_8','OoEP_9','YEiWS_1','YEiWS_2','YEiWS_3','YEiWS_4','YEiWS_5','YEiWS_6',
							'YEiWS_7','YEiWS_8','LFS_1','LFS_2','LFS_3','LFS_4',
							#Fourth Excel Sheet Abbreviations
							'LotE','EPoM_1','EPoM_2','EPoM_3','EPoM_4','CoM_1','CoM_2','CoM_3','MoTtW_1','MoTtW_2','MoTtW_3','MoTtW_4','MoTtW_5','MoTtW_6','MoTtW_7',
							'MoTtW_8','MoTtW_9','MoTtW_10','MoTtW_11','MoTtW_12','MoTtW_13','HbT_1','HbT_2','HbT_3','HbT_4','HbT_5','FbT_1','FbT_2','FbT_3','FbT_4',
							'FbT_5','FbT_6','FbT_7','FbT_8','UW_1','UW_2','UW_3','UW_4','UW_5','AtIaH_1','AtIaH_2','AtIaH_3','AtIaH_4','RaMP_1','RaMP_2','SEIFA_1',
							'SEIFA_2','SEIFA_3','SEIFA_4','LA','PA_1','PA_2','PA_3','PA_4','PA_5','PA_6','PA_7','PA_8','PA_9','PA_10','PA_11','PA_12','PA_13','PA_14',
							'PA_15','SI_1','SI_2'
							),
							c(
							#First Excel Sheet Formal Names
							'District Code','Name of District','Year','Estimated Resident Population_Persons_0-14 Years (%)','Estimated Resident Population_Persons_15-24 Years (%)',
							'Estimated Resident Population_Persons_25-34 Years (%)','Estimated Resident Population_Persons_35-44 Years (%)','Estimated Resident Population_Persons_45-54 Years (%)',
							'Estimated Resident Population_Persons_55-64 Years (%)','Estimated Resident Population_Persons_65-74 Years (%)','Estimated Resident Population_Persons_75-84 Years (%)',
							'Estimated Resident Population_Persons_85 Years and Older (%)','Estimated Resident Population_Males_0-4 Years (no.)','Estimated Resident Population_Males_5-9 Years (no.)',
							'Estimated Resident Population_Males_10-14 Years (no.)','Estimated Resident Population_Males_15-19 Years (no.)','Estimated Resident Population_Males_20-24 Years (no.)',
							'Estimated Resident Population_Males_25-29 Years (no.)','Estimated Resident Population_Males_30-34 Years (no.)','Estimated Resident Population_Males_35-39 Years (no.)',
							'Estimated Resident Population_Males_40-44 Years (no.)','Estimated Resident Population_Males_45-49 Years (no.)','Estimated Resident Population_Males_50-54 Years (no.)',
							'Estimated Resident Population_Males_55-59 Years (no.)','Estimated Resident Population_Males_60-64 Years (no.)','Estimated Resident Population_Males_65-69 Years (no.)',
							'Estimated Resident Population_Males_70-74 Years (no.)','Estimated Resident Population_Males_75-79 Years (no.)','Estimated Resident Population_Males_80-84 Years (no.)',
							'Estimated Resident Population_Males_85 Years and Older (no.)','Estimated Resident Population_Males_Total (no.)','Estimated Resident Population_Females_0-4 Years (no.)',
							'Estimated Resident Population_Females_5-9 Years (no.)','Estimated Resident Population_Females_10-14 Years (no.)','Estimated Resident Population_Females_15-19 Years (no.)',
							'Estimated Resident Population_Females_20-24 Years (no.)','Estimated Resident Population_Females_25-29 Years (no.)','Estimated Resident Population_Females_30-34 Years (no.)',
							'Estimated Resident Population_Females_35-39 Years (no.)','Estimated Resident Population_Females_40-44 Years (no.)','Estimated Resident Population_Females_45-49 Years (no.)',
							'Estimated Resident Population_Females_50-54 Years (no.)','Estimated Resident Population_Females_55-59 Years (no.)','Estimated Resident Population_Females_60-64 Years (no.)',
							'Estimated Resident Population_Females_65-69 Years (no.)','Estimated Resident Population_Females_70-74 Years (no.)','Estimated Resident Population_Females_75-79 Years (no.)',
							'Estimated Resident Population_Females_80-84 Years (no.)','Estimated Resident Population_Females_85 Years and Older (no.)','Estimated Resident Population_Females_Total (no.)',
							'Estimated Resident Population_Persons_0-4 Years (no.)','Estimated Resident Population_Persons_5-9 Years (no.)','Estimated Resident Population_Persons_10-14 Years (no.)',
							'Estimated Resident Population_Persons_15-19 Years (no.)','Estimated Resident Population_Persons_20-24 Years (no.)','Estimated Resident Population_Persons_25-29 Years (no.)',
							'Estimated Resident Population_Persons_30-34 Years (no.)','Estimated Resident Population_Persons_35-39 Years (no.)','Estimated Resident Population_Persons_40-44 Years (no.)',
							'Estimated Resident Population_Persons_45-49 Years (no.)','Estimated Resident Population_Persons_50-54 Years (no.)','Estimated Resident Population_Persons_55-59 Years (no.)',
							'Estimated Resident Population_Persons_60-64 Years (no.)','Estimated Resident Population_Persons_65-69 Years (no.)','Estimated Resident Population_Persons_70-74 Years (no.)',
							'Estimated Resident Population_Persons_75-79 Years (no.)','Estimated Resident Population_Persons_80-84 Years (no.)','Estimated Resident Population_Persons_85 Years and Older (no.)',
							'Estimated Resident Population_Persons_Total (no.)','Estimated Resident Population_Working Age Population (15-64 Years) (%)','Estimated Resident Population_Males_Median Age (years)',
							'Estimated Resident Population_Females_Median Age (years)','Estimated Resident Population_Persons_Median Age (years)','Births and Deaths_Births (no.)','Births and Deaths_Total fertility rate per female (rate)',
							'Births and Deaths_Deaths (no.)','Births and Deaths_Standard Death Rate (no.)','Population Density (persons/square kilometre)','Aboriginal and Torres Strait Islanders_Proportion of Total Population (%)',
							'Overseas Born Population_Born in Oceania, Antarctica excluding Australia (%)','Overseas Born Population_Born in North-West Europe (%)','Overseas Born Population_Born in Southern and Eastern Europe (%)',
							'Overseas Born Population_Born in North Africa and Middle East (%)','Overseas Born Population_Born in South-East Asia (%)','Overseas Born Population_Born in North-East Asia (%)',
							'Overseas Born Population_Born in Southern,Central Asia (%)','Overseas Born Population_Born in Americas (%)','Overseas Born Population_Born in Sub-Saharan Africa (%)','Overseas Born Population_Total (%)',
							'Regional Internal Migration Estimates_Arrivals (no.)','Regional Internal Migration Estimates_Departures (no.)','Regional Internal Migration Estimates_Net Migration (no.)',
							#Second Excel Sheet Formal Names
							'Number of Businesses_Non-employing businesses (no.)','Number of Businesses_1-4 employees (no.)','Number of Businesses_5-19 employees (no.)','Number of Businesses_20 or more employees (no.)',
							'Number of Businesses_Total number of businesses (no.)','Business Entries_Non-employing businesses (no.)','Business Entries_1-4 employees (no.)','Business Entries_5-19 employees (no.)',
							'Business Entries_20 or more employees (no.)', 'Business Entries_Total Business Entries (no.)','Business Exits_Non-employing businesses (no.)','Business Exits_1-4 employees (no.)',
							'Business Exits_5-19 employees (no.)','Business Exits_20 or more employees (no.)','Business Exits_Total Business Exits (no.)','Number of Businesses By Industry_Agriculture, Forestry and Fishing (no.)',
							'Number of Businesses By Industry_Mining (no.)','Number of Businesses By Industry_Manufacturing (no.)','Number of Businesses By Industry_Electricity, Gas, Water & Waste Services (no.)',
							'Number of Businesses By Industry_Construction (no.)','Number of Businesses By Industry_Wholesale trade (no.)','Number of Businesses By Industry_Retail trade (no.)',
							'Number of Businesses By Industry_Accomodation and Food Services (no.)', 'Number of Businesses By Industry_Transport, Postal and Warehousing (no.)',
							'Number of Businesses By Industry_Information Media and Telecommunications (no.)','Number of Businesses By Industry_Financial and Insurance Services (no.)',
							'Number of Businesses By Industry_Rental, Hiring, and Real Estate Services (no.)','Number of Businesses By Industry_Professional Scientific and Technical Services (no.)',
							'Number of Businesses By Industry_Administrative and Support Services (no.)','Number of Businesses By Industry_Public Administration and Safety (no.)',
							'Number of Businesses By Industry_Education and Training (no.)','Number of Businesses By Industry_Health Care and Social Assistance (no.)',
							'Number of Businesses By Industry_Arts and Recreation Services (no.)','Number of Businesses By Industry_Other Services (no.)','Number of Businesses By Industry_Currently Unknown (no.)',
							'Number of Businesses By Industry_Total (no.)','Building Approvals_Private Sector Houses (no.)','Building Approvals_Private Sector Dwellings other than Houses (no.)',
							'Building Approvals_Total Private Sector Dwellings Units (no.)','Building Approvals_Total Dwelling Units (no.)','Building Approvals_Value of Private Section Houses ($m)',
							'Building Approvals_Value of Private Sector Dwellings other than Houses ($m)','Building Approvals_Value of Total Private Section Dwelling Units ($m)',
							'Building Approvals_Value of Total Residential Buildings ($m)','Building Approvals_Value of Total Non-Residential Buildings ($m)','Building Approvals_Value of Total Buildings ($m)',
							'Residential Property Prices-Number of houses transferred (no.)','Residential Property Prices-Median Sale Price ($)','Residential Property Prices-Attached Dwellings (no.)',
							'Residential Property Prices-Attached Dwellings Median Sale Price ($)','Bankrupts with a non-business related or non-stated reason for bankruptcy (no.)',
							'Bankrupts with a business related reason for bankruptcy (no.)','Total number of bankrupts (no.)','Employed by Industry_Agriculture, Forestry and Fishing (no.)',
							'Employed by Industry_Mining (no.)','Employed by Industry_Manufacturing (no.)','Employed by Industry_Electricity, Gas, Water & Waste Services (no.)','Employed by Industry_Construction (no.)',
							'Employed by Industry_Wholesale trade (no.)','Employed by Industry_Retail trade (no.)','Employed by Industry_Accomodation and Food Services (no.)', 'Employed by Industry_Transport, Postal and Warehousing (no.)',
							'Employed by Industry_Information Media and Telecommunications (no.)','Employed by Industry_Financial and Insurance Services (no.)','Employed by Industry_Rental, Hiring, and Real Estate Services (no.)',
							'Employed by Industry_Professional Scientific and Technical Services (no.)','Employed by Industry_Administrative and Support Services (no.)','Employed by Industry_Public Administration and Safety (no.)',
							'Employed by Industry_Education and Training (no.)','Employed by Industry_Health Care and Social Assistance (no.)','Employed by Industry_Arts and Recreation Services (no.)',
							'Employed by Industry_Other Services (no.)','Employed by Industry_Total (no.)',"Registered Motor Vehicles_Passenger vehicles (no.)","Registered Motor Vehicles_Campervans (no.)",
							"Registered Motor Vehicles_Light commercial vehicles (no.)","Registered Motor Vehicles_Light rigid trucks (no.)","Registered Motor Vehicles_Heavy rigid trucks (no.)",
							"Registered Motor Vehicles_Articulated trucks (no.)","Registered Motor Vehicles_Non-freight carrying trucks (no.)","Registered Motor Vehicles_Buses (no.)","Registered Motor Vehicles_Motorcycles (no.)",
							"Registered Motor Vehicles_Total Vehicles (no.)","Registered Motor Vehicles_Petrol (no.)","Registered Motor Vehicles_Diesel (no.)","Registered Motor Vehicles_LPG/Dual/Other (no.)",
							"Registered Motor Vehicles_Electric (no.)","Registered Motor Vehicles Age_Less than 5 years (no.)","Registered Motor Vehicles Age_5 to 10 years (no.)","Registered Motor Vehicles Age_Over 10 years (no.)",
							#Third Excel Sheet Formal Names
							"Estimates of Personal Income_Median Employee income ($)","Estimates of Personal Income_Total Employee income ($m)","Estimates of Personal Income_Employee income earners (no.)",
							"Estimates of Personal Income_Median Own unincorporated business income ($)","Estimates of Personal Income_Total Own unincorporated business income ($m)",
							"Estimates of Personal Income_Own unincorporated business income earners (no.)","Estimates of Personal Income_Median Investment income ($)","Estimates of Personal Income_Total Investment income ($m)",
							"Estimates of Personal Income_Investment income earners (no.)","Estimates of Personal Income_Median Superannuation and annuity income ($)","Estimates of Personal Income_Total Superannuation and annuity income ($m)",
							"Estimates of Personal Income_Superannuation and annuity income earners (no.)","Estimates of Personal Income_Median Other income (excl. Government pensions) ($)",
							"Estimates of Personal Income_Total Other income (excl. Government pensions) ($m)","Estimates of Personal Income_Other income earners (excl. Government pensions) (no.)","Estimates of Personal Income_Median Total income (excl. Government pensions) ($)",
							"Estimates of Personal Income_Total income (excl. Government pensions) ($m)","Estimates of Personal Income_ Total income earners (excl. Government pensions) (no.)","Selected Government Pensions and Allowances_Age Pension - Centrelink (no.)",
							"Selected Government Pensions and Allowances_Age Pension - DVA (no.)","Selected Government Pensions and Allowances_Service Pension - DVA (no.)","Selected Government Pensions and Allowances_Income Support Supplement - DVA (no.)",
							"Selected Government Pensions and Allowances_Carer Payment (no.)","Selected Government Pensions and Allowances_Disability Support Pension (no.)","Selected Government Pensions and Allowances_Newstart Allowance (no.)",
							"Selected Government Pensions and Allowances_Newstart Allowance - more than 365 days (%)","Selected Government Pensions and Allowances_Parenting Payment - Single (no.)",
							"Selected Government Pensions and Allowances_Youth Allowance (Full time students/apprentices) (no.)","Selected Government Pensions and Allowances_Youth Allowance (Other) (no.)","Selected Government Pensions and Allowances_Family Tax Benefit A (no.)",
							"Selected Government Pensions and Allowances_Family Tax Benefit B (no.)","Selected Government Pensions and Allowances_Total Family Tax Benefit recipients (no.)",
							"Persons with Post School Qualifications_Percentage of total population aged 15 years and over (%)","Persons with Post School Qualifications_Postgraduate degree (%)","Persons with Post School Qualifications_Graduate Diploma, Graduate Certificate (%)",
							"Persons with Post School Qualifications_Bachelor Degree (%)","Persons with Post School Qualifications_Advanced Diploma, or Diploma  (%)","Persons with Post School Qualifications_Certificate (%)",
							"Persons with Post School Qualifications_Inadequately described, not stated (%)","Occupation of Employed Persons_Managers (%)","Occupation of Employed Persons_Professionals (%)","Occupation of Employed Persons_Technicians and Trades Workers (%)",
							"Occupation of Employed Persons_Community, Personal Service Workers (%)","Occupation of Employed Persons_Clerical, Administrative Workers (%)","Occupation of Employed Persons_Sales Workers (%)","Occupation of Employed Persons_Machinery Operators, Drivers (%)",
							"Occupation of Employed Persons_Labourers (%)","Occupation of Employed Persons_Inadequately Described, Not Stated (%)","Youth Engagement in Work/Study_Working full-time & studying part-time (%)","Youth Engagement in Work/Study_Working part-time & studying part-time (%)",
							"Youth Engagement in Work/Study_Working part-time & studying full-time (%)","Youth Engagement in Work/Study_Working full-time (not studying) (%)","Youth Engagement in Work/Study_Studying full-time (not working) (%)",
							"Youth Engagement in Work/Study_Working full-time & studying full-time (%)","Youth Engagement in Work/Study_Fully engaged (%)","Youth Engagement in Work/Study_Total - aged 15-19 years (%)","Labour Force Statistics_Labour Force (no.)",
							"Labour Force Statistics_Unemployed (no.)","Labour Force Statistics_Unemployment Rate (%)","Labour Force Statistics_Participation Rate (%)",
							#Fourth Excel Sheet Formal Names
							"Speaks a language other than English at home (%)","English Proficiency of Migrants_Only English spoken at home (%)","English Proficiency of Migrants_Proficient in spoken English (%)","English Proficiency of Migrants_Not proficient in spoken English (%)",
							"English Proficiency of Migrants_Proficiency not stated (%)","Citizenship of Migrants_Australian citizen (%)","Citizenship of Migrants_Not an Australian citizen (%)","Citizenship of Migrants_Citizenship not stated (%)",
							"Method of Travel to Work_Used one method - Train or tram (no.)","Method of Travel to Work_Used one method - Bus (no.)","Method of Travel to Work_Used one method - Car (no.)","Method of Travel to Work_Used one method - Motor bike/scooter (no.)",
							"Method of Travel to Work_Used one method - Bicycle (no.)","Method of Travel to Work_Used one method - Other (no.)","Method of Travel to Work_Used one method - Walked only (no.)","Method of Travel to Work_Total used one method (no.)",
							"Method of Travel to Work_Total used more than one method (no.)","Method of Travel to Work_Other - Worked from home (no.)","Method of Travel to Work_Other - Employed but did not go to work (no.)","Method of Travel to Work_Other - Method of travel not stated (no.)",
							"Method of Travel to Work_Total employed (no.)","Households by Type_Lone person households (no.)","Households by Type_Group households (no.)","Households by Type_Family households (no.)","Households by Type_Total households (no.)",
							"Households by Type_Average Household Size (no.)","Families by Type_Couple families with children under 15 and/or dependent students (no.)","Families by Type_Couple families with non-dependent children only (no.)","Families by Type_Couple families without children (no.)",
							"Families by Type_One parent families, children under 15 &/or dependent students (no.)","Families by Type_One parent families, non-dependent children only (no.)","Families by Type_Other families (no.)","Families by Type_Total families (no.)",
							"Families by Type_Average Family Size (no.)","Unpaid Work_Persons undertaking voluntary work for an organisation or group (%)","Unpaid Work_Persons caring for own children without pay (%)","Unpaid Work_Persons caring for other children without pay (%)",
							"Unpaid Work_Persons caring for own and other children without pay (%)","Unpaid Work_Persons providing unpaid care, help or assistance to others (%)","Access to Internet at Home_Broadband connection (%)","Access to Internet at Home_Dial-up connection (%)",
							"Access to Internet at Home_Other (%)","Access to Internet at Home_Total internet connections (%)","Rent and Mortgage Repayments_Average monthly household rental payment ($)","Rent and Mortgage Repayments_Average monthly household mortgage payment ($)",
							"SEIFA Decile Ranking_Advantage and disadvantage (no.)","SEIFA Decile Ranking_Disadvantage (no.)","SEIFA Decile Ranking_Economic Resources (no.)","SEIFA Decile Ranking_Education & Occupation (no.)","LAND AREA (ha)","Protected Areas_ Indigenous Protected Area (no.)",
							"Protected Areas_National Parks (no.)","Protected Areas_Nature Reserves (no.)","Protected Areas_All Other Protected Areas (no.)","Protected Areas_Total (no.)","Protected Areas_ Indigenous Protected Area (ha)","Protected Areas_National Parks (ha)",
							"Protected Areas_Nature Reserves (ha)","Protected Areas_All Other Protected Areas (ha)","Protected Areas_Total (ha)","Protected Areas_ Indigenous Protected Area (%)","Protected Areas_National Parks (%)","Protected Areas_Nature Reserves (%)",
							"Protected Areas_All Other Protected Areas (%)","Protected Areas_Total (%)","Solar Installations_Small-Scale Solar Panel System Installations (no.)","Solar Installations_Solar Water Heater Installations (no.)"))

	#Read in first excel sheet on People and Population
	data_pp <- read_excel("14100DS0002_2017-03.xlsx", 
												   sheet = 1,
												   col_names=TRUE,
												   skip=8) #Header on row 9, data starts row 10

	#Better headers for future reference;potential headers in xlsx files are either too wordy or hard to differentiate
	names(data_pp) <- legend_table[1:92,1]

	#Read in second excel sheet on economy and industry
	data_ei <- read_excel("14100DS0004_2017-03.xlsx", 
												   sheet = 1,
												   col_names=TRUE,
												   skip=7) #Header on row 8, data starts row 9

	#Better headers for future reference;potential headers in xlsx files are either too wordy or hard to differentiate
	names(data_ei) <- legend_table[c(1:3,93:182),1]

	#Read in third excel sheet on income
	data_money <- read_excel("14100DS0006_2017-03.xlsx", 
												   sheet = 1,
												   col_names=TRUE,
												   skip=7) #Header on row 8, data starts row 9

	#Better headers for future reference;potential headers in xlsx files are either too wordy or hard to differentiate
	names(data_money) <- legend_table[c(1:3,183:242),1]

	#Read in third excel sheet on income
	data_fcle <- read_excel("14100DS0008_2017-03.xlsx", 
												   sheet = 1,
												   col_names=TRUE,
												   skip=7) #Header on row 8, data starts row 9

	#Better headers for future reference;potential headers in xlsx files are either too wordy or hard to differentiate
	names(data_fcle) <- legend_table[c(1:3,243:309),1]

	data_merged_temp1 <- merge(y=data_ei,x=data_pp,by=c("Code","Label","Year"), all.x = TRUE,all.Y=TRUE)
	data_merged_temp2 <- merge(y=data_money,x=data_fcle,by=c("Code","Label","Year"), all.x = TRUE,all.Y=TRUE)
	data_merged <- merge(y=data_merged_temp1,x=data_merged_temp2,by=c("Code","Label","Year"), all.x = TRUE,all.Y=TRUE)

	plot_scatter <- function(index_x, index_y, startfromorigin=FALSE, labeltitle, labelsubtitle='', labelx,labely){
	  plot_temp<-cbind.data.frame(data_merged[,index_x],data_merged[,index_y])
	  #Get rid of null values
	  plot_temp<-plot_temp[-which(plot_temp[,1]=="-"),] #Removes rows with '-'
	  plot_temp<-plot_temp[-which(plot_temp[,2]=="-"),] #Removes rows with '-'
	  plot_temp<-plot_temp[!is.na(as.numeric(plot_temp[,2])),] #Removes rows with values that are non-convertible to numerical values 
	  plot_temp<-plot_temp[!is.na(as.numeric(plot_temp[,1])),] #Removes rows with values that are non-convertible to numerical values 
	  #Convert to continuous - if you leave out these lines, graph becomes a mess of discrete points
	  plot_temp[,1] <- as.numeric(as.vector(plot_temp[,1]))
	  plot_temp[,2] <- as.numeric(as.vector(plot_temp[,2]))
	  #Regression line - "line of best fit"; finding the intercept and gradient
	  if(nrow(plot_temp)>0){
		ablinetemp<-coef(lm(plot_temp[,2] ~ plot_temp[,1]))
		if(missing(labelx)){
		  if(is.numeric(index_x)){
			labelx=legend_table[index_x,2] 
		  }else{
			labelx=legend_table[which(legend_table[,1]==index_x),2]
		  }
		}
		if(missing(labely)){
		  if(is.numeric(index_y)){
			labely=legend_table[index_y,2]
		  }else{
			labely=legend_table[which(legend_table[,1]==index_y),2]
		  }
		}
		if(missing(labeltitle)){
			labeltitle=paste(labelx, " against ", labely, sep='')
		}
			   #Graph the line
					a <- ggplot(data=plot_temp,aes(x=plot_temp[,1],y=plot_temp[,2]))+
					  geom_point()+
					  geom_abline(intercept = as.numeric(ablinetemp)[1], slope = as.numeric(ablinetemp)[2],colour='#FF0000')+
					  geom_smooth(span=0.25)+
					  labs(title=labeltitle,subtitle=labelsubtitle,
						   x=labelx,y=labely)
					if(startfromorigin==TRUE){
					  a <- a + expand_limits(x = 0, y = 0)
					}
				ggsave(paste(as.numeric(as.POSIXct(Sys.time())),'.png',sep='')) #timestamp for unique file names.
			  return(NULL)
	  } else {
		print("Zero rows in the temporary matrix. Aborting.")
		return(NULL);
	  }
	}



	

	plot_scatter("Abo_TorIsl", "BaD_4", TRUE, labelx="Indigenous Proportion of Population (%)",labely="Standard Death Rate", labeltitle="Indigenous Population Proportion against the Standard Death Rate")
	plot_scatter("Abo_TorIsl","AtIaH_1", TRUE, labelx="Indigenous Proportion of Population (%)", labely="Access to Broadband Internet (%)", labeltitle="Indigenous Populations and their access to internet")
	plot_scatter("AtIaH_1","BaD_4", TRUE, labelx="Access to Broadband Internet (%)", labely="Standard Death Rate", labeltitle="Correlation between access to internet and mortality rates")
	plot_scatter("SGPaA_6","BaD_3", TRUE, labelx="Disability Pensions (no.)", labely="Number of Deaths (no.)", labeltitle="Death Rate against number of Disability Pensions")

	#Education and mortality
	#Combine all education columns
	plot1_temp <-cbind(data_merged[,"PwPSQ_2"],data_merged[,"PwPSQ_3"],data_merged[,"PwPSQ_4"],data_merged[,"PwPSQ_5"],data_merged[,"PwPSQ_6"])
	#Convert to numeric
	plot1_temp <- matrix(as.numeric(unlist(plot1_temp)),nrow=nrow(plot1_temp))
	#Sum education columns
	plot1_data1 <- rowSums(plot1_temp)
	#Merge columns that we are comparing
	plot1<-cbind.data.frame(plot1_data1,data_merged[,'BaD_4'])
	#Get rid of null values
	plot1<-plot1[!is.na(plot1[,1]),] #Removes NA values
	plot1<-plot1[-which(plot1[,2]=="-"),] #Removes rows with '-'
	#Convert to continuous - if you leave out these lines, graph becomes a mess of discrete points
	plot1[,1] <- as.numeric(as.vector(plot1[,1]))
	plot1[,2] <- as.numeric(as.vector(plot1[,2]))
	#Regression line - "line of best fit"; finding the intercept and gradient
	temp<-coef(lm(plot1[,2] ~ plot1[,1]))
	#Graph the line
	ggplot(data=plot1,aes(x=plot1[,1],y=plot1[,2]))+geom_point()+geom_abline(intercept = as.numeric(temp)[1], slope = as.numeric(temp)[2],colour='#FF0000')+scale_y_continuous(name="Standard Death Rate",breaks=seq(0,16,2),limits=c(0,16))+scale_x_continuous(name="Population Percentage with Post School Qualifications")+ggtitle("Education and Mortality")+geom_smooth(span=0.25)
	ggsave(paste(as.numeric(as.POSIXct(Sys.time())),'.png',sep=''))
	
	#Indigenous Australians against Median Income
	plot2_data1 <- data_money[which(data_money[,"Year"]==2013),]
	plot2_data2 <- data_pp[which(data_pp[,"Year"]==2011),]
	#Merge columns that we are comparing
	data_merged_plot2 <- merge(y=plot2_data1,x=plot2_data2,by=c("Code","Label"), all.x = TRUE,all.Y=TRUE)
	#Basically nothing happens, but just changing variable name so that it is more consistent with previous code
	plot2<-cbind.data.frame(data_merged_plot2[,"Abo_TorIsl"],data_merged_plot2[,"EoPI_16"])
	#Get rid of null values
	plot2<-plot2[!is.na(plot2[,1]),] #Removes NA values
	plot2<-plot2[-which(plot2[,2]=="-"),] #Removes rows with '-'
	#Convert to continuous - if you leave out these lines, graph becomes a mess of discrete points
	plot2[,1] <- as.numeric(as.vector(plot2[,1]))
	plot2[,2] <- as.numeric(as.vector(plot2[,2]))
	#Regression line - "line of best fit"; finding the intercept and gradient
	temp<-coef(lm(plot2[,2] ~ plot2[,1]))
	#Graph the line
	ggplot(data=plot2,aes(x=plot2[,1],y=plot2[,2]))+geom_point()+geom_abline(intercept = as.numeric(temp)[1], slope = as.numeric(temp)[2],colour='#FF0000')+scale_y_continuous(name="Median Income in 2013 ($)")+scale_x_continuous(name="Aboriginal and Torres Strait Islander Percentage of Population in 2011 (%)")+ggtitle("Population of Indigenous Australians against Median Income")+geom_smooth(span=0.25)
	ggsave(paste(as.numeric(as.POSIXct(Sys.time())),'.png',sep=''))